class Juego {
  //CAMPOS
  //LOGICA DE ESTADO - JUEGO (GANAR O PERDER)
  
  //IMAGENES

  //LLAMAR A LAS DEMAS CLASES QUE ESTARAN DENTRO DEL JUEGO

  //CONSTRUCTOR - SETUP DE LA CLASE
  Juego() {
    //DECLARAR LAS DEMAS CLASES
    
    //DECLARAR LOS ATRIBUTOS CORRESPONDIENTES
  }  

  //METODOS 
  //DRAW DE LA CLASE
  void dibujar() {
    //HACER USO DE LOS DIFERENTES ESTADOS DEL JUEGO
  }
  //MOVIMIENTO DE LOS OBJETOS DEL JUEGO
  void movimiento() {
  }

  //ACTUALIZAR LOS VALORES
  void actualizar() {
  }

  //EVENTO DEL MOUSE
  void mouse() {
  }
}
